default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: R$#tMY$qlRY002
  host: 50.116.12.246




development:
  <<: *default
  # database: referralyogi_development
  database: referralyogi_staging
test:
  <<: *default
  database: referralyogi_test
production:
  <<: *default
  database: referralyogi_production
staging:
  <<: *default
  database: referralyogi_staging